# Site settings
title: O Grande Livro dos Erros Makers
email: edu@edulopes.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/ograndelivro/" # the subpath of your site, e.g. /blog/
url: "http://www.edulopes.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
